# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataformat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataformat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x64\x61taformat.proto\"a\n\nDataFormat\x12\x1b\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32\t.DataType\x12\x10\n\x08mimeType\x18\x02 \x01(\t\x12\x13\n\x0bpixelFormat\x18\x03 \x01(\t\x12\x0f\n\x07\x64imSize\x18\x04 \x03(\x05\"$\n\nLinkSwitch\x12\x16\n\x0estubDeviceGuid\x18\x01 \x01(\t\"\xa6\x01\n\tDataFrame\x12\x15\n\rsenderBlkGuid\x18\x01 \x01(\t\x12\x12\n\nsenderPort\x18\x02 \x01(\t\x12\x17\n\x0freceiverBlkGuid\x18\x03 \x01(\t\x12\x14\n\x0creceiverPort\x18\x04 \x01(\t\x12\x1b\n\x06\x66ormat\x18\x05 \x01(\x0b\x32\x0b.DataFormat\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x0f\n\x07\x64\x61taptr\x18\x07 \x01(\x03*-\n\x08\x44\x61taType\x12\x0c\n\x08\x44\x41TA_RAW\x10\x00\x12\x13\n\x0f\x44\x41TA_COMPRESSED\x10\x01\x62\x06proto3')
)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DATA_RAW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_COMPRESSED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=326,
  serialized_end=371,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
DATA_RAW = 0
DATA_COMPRESSED = 1



_DATAFORMAT = _descriptor.Descriptor(
  name='DataFormat',
  full_name='DataFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataType', full_name='DataFormat.dataType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mimeType', full_name='DataFormat.mimeType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixelFormat', full_name='DataFormat.pixelFormat', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimSize', full_name='DataFormat.dimSize', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=117,
)


_LINKSWITCH = _descriptor.Descriptor(
  name='LinkSwitch',
  full_name='LinkSwitch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stubDeviceGuid', full_name='LinkSwitch.stubDeviceGuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=155,
)


_DATAFRAME = _descriptor.Descriptor(
  name='DataFrame',
  full_name='DataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderBlkGuid', full_name='DataFrame.senderBlkGuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='senderPort', full_name='DataFrame.senderPort', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiverBlkGuid', full_name='DataFrame.receiverBlkGuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiverPort', full_name='DataFrame.receiverPort', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='DataFrame.format', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DataFrame.timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataptr', full_name='DataFrame.dataptr', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=324,
)

_DATAFORMAT.fields_by_name['dataType'].enum_type = _DATATYPE
_DATAFRAME.fields_by_name['format'].message_type = _DATAFORMAT
DESCRIPTOR.message_types_by_name['DataFormat'] = _DATAFORMAT
DESCRIPTOR.message_types_by_name['LinkSwitch'] = _LINKSWITCH
DESCRIPTOR.message_types_by_name['DataFrame'] = _DATAFRAME
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataFormat = _reflection.GeneratedProtocolMessageType('DataFormat', (_message.Message,), dict(
  DESCRIPTOR = _DATAFORMAT,
  __module__ = 'dataformat_pb2'
  # @@protoc_insertion_point(class_scope:DataFormat)
  ))
_sym_db.RegisterMessage(DataFormat)

LinkSwitch = _reflection.GeneratedProtocolMessageType('LinkSwitch', (_message.Message,), dict(
  DESCRIPTOR = _LINKSWITCH,
  __module__ = 'dataformat_pb2'
  # @@protoc_insertion_point(class_scope:LinkSwitch)
  ))
_sym_db.RegisterMessage(LinkSwitch)

DataFrame = _reflection.GeneratedProtocolMessageType('DataFrame', (_message.Message,), dict(
  DESCRIPTOR = _DATAFRAME,
  __module__ = 'dataformat_pb2'
  # @@protoc_insertion_point(class_scope:DataFrame)
  ))
_sym_db.RegisterMessage(DataFrame)


# @@protoc_insertion_point(module_scope)
